# ***Introduction Numpy***

In [1]:
import numpy as np

> what is an array?

    An array is a data structure in programming that stores a collection of elements, typically of the same data type, in a contiguous block of memory. It is a fundamental concept in many programming languages, including Python, and is used extensively in scientific computing, data analysis and machine learning.

    In python, the Numpy library provides support for arrays and enables efficient numerical operations on them. Numpy arrays are more effieent than python lists for numerical operations because they are implemented in C and allow for vectorized operations.


In [2]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [4]:
a3 = a[np.newaxis, :]
print(a3)
a3.shape

[[0 1 2 3 4 5]]


(1, 6)

### Creating Arrays with Numpy

In [5]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6), (4,5,6,7,8,9)])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
(2, 6)


In [6]:
print(type(a)) # type of array
print(a.dtype) 

<class 'numpy.ndarray'>
int32


### Initialize Array

In [7]:
zeros = np.zeros((2, 5)) # (rows, columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
zeros.dtype

dtype('float64')

In [9]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
full = np.full((2, 5), 7.5)
full

array([[7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5]])

In [12]:
full.dtype

dtype('float64')

In [13]:
identity = np.eye(5) # creating an identity matrix
print(identity)
print(identity.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
float64


### Attributes of Array

In [14]:
print(a.shape)  # shape of array
print(len(a)) # guve us the length elements of array
print(a.ndim) # give us the dimension of array
print(a.size) # give us the numbers of elements in array

(6,)
6
1
6


### Basic operations

In [15]:
g = a - b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3]])

In [16]:
# addition 
h = a+b
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [17]:
# another of add
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [18]:
# multiply
s = a*b
s

array([[ 1,  4,  9, 16, 25, 36],
       [ 4, 10, 18, 28, 40, 54]])

In [19]:
# divide
j = a/b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667]])

In [20]:
# square of each element
k = a **2
k

array([ 1,  4,  9, 16, 25, 36])

In [21]:
empty = np.empty((2, 4))
print(empty)
print("------------")
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------
[0. 0. 0. 0.]


In [22]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [23]:
# array of even numbers from 0 to 23
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [24]:
# array of odd numbers from 0 to 23
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [25]:
# specific differnce between numbers
diff = np.arange(0, 23, 0.515) # 0.515 is the difference between numbers
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

In [26]:
lin = np.linspace(0, 10, num=15)
lin

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [27]:
lin.dtype

dtype('float64')

In [28]:
# define the dtype of array
x = np.arange(0 ,22.6, 1.5, dtype=np.int8)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int8)

In [ ]:
# Assignment: What is the difference between int32, 64 ya float 32, 64, 16..... In ka matlab kia hy? Why do we use one and not the other one?

In [29]:
# sorting an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [30]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [32]:
# concatenate these arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Concatenate 2D Arrays

In [33]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6]]) # 1x2 array

In [34]:
len(x)

2

In [35]:
len(y)

1

In [36]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
w = np.array([[5,1], [7,1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array

In [38]:
z1 = np.concatenate((w,x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [39]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [40]:
len(array_example)

3

In [41]:
array_example.size

24

In [42]:
array_example.dtype

dtype('int32')

In [43]:
array_example.shape

(3, 2, 4)

In [44]:
# creata 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                          [[4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])
a1.shape

(3, 1, 4)

In [45]:
# reshape the a 
a2 = a1.reshape(6,2)
a2.shape

(6, 2)

In [46]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [47]:
a2.reshape(3,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [48]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [49]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [50]:
c = a[: , np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

indexing and slicing

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [53]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [56]:
# filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

In [57]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [59]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Numpy Indexing and Slicing

In [2]:
# create an array
a = np.array([1,2,3,4,5,6,7])
print(a)
print(a[-1])
print(a[1:5])

[1 2 3 4 5 6 7]
7
[2 3 4 5]


In [3]:
b = np.arange(0,12, 2)
print(b)
print(b[2])

[ 0  2  4  6  8 10]
4


In [5]:
c = b.reshape(3, 2)
print(c)
print(c[1])
print(c[(c < 5) | (c > 7)])
print(c[(c < 5) & (c > 7)])

[[ 0  2]
 [ 4  6]
 [ 8 10]]
[4 6]
[ 0  2  4  8 10]
[]


### Noted: Enlist Boolean Operators and Conditional Operators  

In [6]:
# numpy Matrix or matrices
# create a matrix of 2 x 3
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
# create a matrix of big dimension
b = np.arange (0,100,2).reshape(5,10)
print(b)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [10]:
# slicing a matrix 
c[1:3, 3:5] # range define of rows and columns
print(c)
print(c.max(axis=0)) # only for column
print(c.max(axis=1)) # only for row
print(c.min())
print(c.sum())

[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 8 10]
[ 2  6 10]
0
30


In [18]:
m = np.arange(0,50,2)
print(m)
print(m+np.array([2,10]))
print(np.vstack((m , np.array([42,44]))))
print(m * np.array([20,22]))
print(m - np.array([20,22]))
print(np.flip(c))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


ValueError: operands could not be broadcast together with shapes (25,) (2,) 